{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "49c0ae32",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Loading required package: agridat\n",
      "\n",
      "Loading required package: reshape2\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<table class=\"dataframe\">\n",
       "<caption>A matrix: 8 × 3 of type dbl</caption>\n",
       "<thead>\n",
       "\t<tr><th scope=col>result.non</th><th scope=col>result.mean</th><th scope=col>result.sd</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "\t<tr><td>0.057</td><td>0.049</td><td>0.059</td></tr>\n",
       "\t<tr><td>0.054</td><td>0.046</td><td>0.045</td></tr>\n",
       "\t<tr><td>0.048</td><td>0.061</td><td>0.056</td></tr>\n",
       "\t<tr><td>0.049</td><td>0.068</td><td>0.053</td></tr>\n",
       "\t<tr><td>0.048</td><td>0.041</td><td>0.044</td></tr>\n",
       "\t<tr><td>0.043</td><td>0.051</td><td>0.052</td></tr>\n",
       "\t<tr><td>0.046</td><td>0.053</td><td>0.045</td></tr>\n",
       "\t<tr><td>0.045</td><td>0.000</td><td>0.048</td></tr>\n",
       "</tbody>\n",
       "</table>\n"
      ],
      "text/latex": [
       "A matrix: 8 × 3 of type dbl\n",
       "\\begin{tabular}{lll}\n",
       " result.non & result.mean & result.sd\\\\\n",
       "\\hline\n",
       "\t 0.057 & 0.049 & 0.059\\\\\n",
       "\t 0.054 & 0.046 & 0.045\\\\\n",
       "\t 0.048 & 0.061 & 0.056\\\\\n",
       "\t 0.049 & 0.068 & 0.053\\\\\n",
       "\t 0.048 & 0.041 & 0.044\\\\\n",
       "\t 0.043 & 0.051 & 0.052\\\\\n",
       "\t 0.046 & 0.053 & 0.045\\\\\n",
       "\t 0.045 & 0.000 & 0.048\\\\\n",
       "\\end{tabular}\n"
      ],
      "text/markdown": [
       "\n",
       "A matrix: 8 × 3 of type dbl\n",
       "\n",
       "| result.non | result.mean | result.sd |\n",
       "|---|---|---|\n",
       "| 0.057 | 0.049 | 0.059 |\n",
       "| 0.054 | 0.046 | 0.045 |\n",
       "| 0.048 | 0.061 | 0.056 |\n",
       "| 0.049 | 0.068 | 0.053 |\n",
       "| 0.048 | 0.041 | 0.044 |\n",
       "| 0.043 | 0.051 | 0.052 |\n",
       "| 0.046 | 0.053 | 0.045 |\n",
       "| 0.045 | 0.000 | 0.048 |\n",
       "\n"
      ],
      "text/plain": [
       "     result.non result.mean result.sd\n",
       "[1,] 0.057      0.049       0.059    \n",
       "[2,] 0.054      0.046       0.045    \n",
       "[3,] 0.048      0.061       0.056    \n",
       "[4,] 0.049      0.068       0.053    \n",
       "[5,] 0.048      0.041       0.044    \n",
       "[6,] 0.043      0.051       0.052    \n",
       "[7,] 0.046      0.053       0.045    \n",
       "[8,] 0.045      0.000       0.048    "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "rm(list = ls())\n",
    "set.seed(42)\n",
    "require(agridat)\n",
    "require(reshape2)\n",
    "data(kang.peanut)\n",
    "Y0 <- acast(kang.peanut, gen~env, value.var=\"yield\", fun.aggregate = mean)\n",
    "simple_parametric_t_statistic <- function(Y0, method, B) {\n",
    "    n <- nrow(Y0)\n",
    "    p <- ncol(Y0)\n",
    "    M <- min(n - 1, p)\n",
    "    T.boot <- matrix(NA, nrow = B, ncol = M - 1)\n",
    "    if (method == \"non-scaled\"){\n",
    "        Y <- scale(Y0, center = TRUE, scale = FALSE)\n",
    "        svd.Y <- svd(Y)\n",
    "        lambda <- svd.Y$d\n",
    "        for(Component in 1:(M - 1)){\n",
    "            K <- Component - 1\n",
    "            for(Boot in 1:B){\n",
    "                E.boot <- matrix(rnorm((n - 1 - K)*(p - K)), nrow = n - 1 - K, ncol = p - K)\n",
    "                lambda.boot <- svd(E.boot)$d\n",
    "                T.boot[Boot, Component] <- lambda.boot[1]^2 / sum(lambda.boot^2)\n",
    "            }\n",
    "    }\n",
    "    }\n",
    "    \n",
    "    if (method == \"scale-mean\"){\n",
    "        means.Y0 <- apply(Y0, 2, mean)\n",
    "        Y <- scale(Y0, center = TRUE, scale = means.Y0)\n",
    "        svd.Y <- svd(Y)\n",
    "        lambda <- svd.Y$d\n",
    "        for(Component in 1:(M - 1)){\n",
    "            K <- Component - 1\n",
    "            for(Boot in 1:B){\n",
    "                E.boot <- matrix(rnorm((n - 1 - K)*(p - K)), nrow = n - 1 - K, ncol = p - K)\n",
    "                means.E <- apply(E.boot, 2, mean)\n",
    "                E <- scale(E.boot, center = TRUE, scale = means.E)\n",
    "                lambda.boot <- svd(E)$d\n",
    "                T.boot[Boot, Component] <- lambda.boot[1]^2 / sum(lambda.boot^2)\n",
    "            }\n",
    "    \n",
    "    }\n",
    "    }\n",
    "    \n",
    "    if (method == \"scale-sd\"){\n",
    "        Y <- scale(Y0, center = TRUE, scale = TRUE)\n",
    "        svd.Y <- svd(Y)\n",
    "        lambda <- svd.Y$d\n",
    "        for(Component in 1:(M - 1)){\n",
    "            K <- Component - 1\n",
    "            for(Boot in 1:B){\n",
    "                E.boot <- matrix(rnorm((n - 1 - K)*(p - K)), nrow = n - 1 - K, ncol = p - K)\n",
    "                E <- scale(E.boot, center = TRUE, scale = TRUE)\n",
    "                lambda.boot <- svd(E.boot)$d\n",
    "                T.boot[Boot, Component] <- lambda.boot[1]^2 / sum(lambda.boot^2)\n",
    "            }\n",
    "    \n",
    "    }\n",
    "    }\n",
    "    T.boot\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "simulation_test <- function(Y0, method, alpha, B.boot, B.resample) {\n",
    "    t_boot_table <- simple_parametric_t_statistic(Y0, method, B.boot)\n",
    "    ci <- apply(t_boot_table, 2, quantile, probs = c(alpha/2, 1-alpha/2))\n",
    "    t_resample_table <- simple_parametric_t_statistic(Y0, method, B.resample)\n",
    "    rowMeans(apply(t_resample_table, 1, function(row) (row < ci[1,]))) + rowMeans(apply(t_resample_table, 1, function(row) (row > ci[2,]))) \n",
    "}\n",
    "result.non <- simulation_test(Y0, \"non-scaled\", 0.05, 100000, 1000)\n",
    "result.mean <- simulation_test(Y0, \"scale-mean\", 0.05, 100000, 1000)\n",
    "result.sd <- simulation_test(Y0, \"scale-sd\", 0.05, 100000, 1000)\n",
    "cbind(result.non,result.mean, result.sd)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b34e8e9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R 4.2.2",
   "language": "R",
   "name": "ir422"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.2.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
